server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: D:\tasks\jwtWithAccessRights\certificate.p12
    key-store-password: 1PwCgNAb
spring:
  datasource:
    username: egor
    password: 123
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect